modLoader="javafml"
loaderVersion="[${forge_loader_version},)"
license="${mod_license}"

[[mods]]
modId="kuvalich"
version="${version}"
displayName="${mod_name}"
updateJSONURL="https://www.curseforge.com/minecraft/mc-mods/kuvalich"
displayURL="https://www.curseforge.com/minecraft/mc-mods/kuvalich"
logoFile=""
credits="特别感谢 白狐大小姐 为本项目提供的支持和帮助"
authors="${mod_author}"
description='''
Warframe!
'''

[[dependencies.kuvalich]]
modId="forge"
mandatory=true
versionRange="[${forge_loader_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.kuvalich]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.kuvalich]]
modId="geckolib"
mandatory=true
versionRange="[4.4,)"
ordering="AFTER"
side="BOTH"

[[mixins]]
config = "kuvalich.mixins.json"

[[mixins]]
config = "kuvalich.tacz.mixins.json"

[[dependencies.kuvalich]]
modId="patchouli"
mandatory=false
versionRange="[1.20.1-84,)"
ordering="AFTER"
side="BOTH"